### ISSUE TITLE
Problum with validation input value.

### ISSUE THREAD

**Issue by MrAbbosov** [pro100Sardor/fizzBuzz#1]
![Screenshot_7](https://user-images.githubusercontent.com/68499298/98615305-18f99b80-231c-11eb-9b9d-7cb3708fcc9e.png)
Агар кодни иннспект килиб текстга узгартирилса, инпутдаги киймат текширилмаяпти.

**Comment by MrAbbosov** [comment]
![Screenshot_10](https://user-images.githubusercontent.com/68499298/98615818-498e0500-231d-11eb-9817-5e7ea1108a3b.png)
Минус кийматларни хам кабул киляпти

**Comment by sardorbek-jurakulov** [comment]
> ![Screenshot_7](https://user-images.githubusercontent.com/68499298/98615305-18f99b80-231c-11eb-9b9d-7cb3708fcc9e.png)
> Агар кодни иннспект килиб текстга узгартирилса, инпутдаги киймат текширилмаяпти.

sfasdfasdfasdf

**Comment by sardorbek-jurakulov** [comment]
problem solved, thanks
